language: objective-c
before_install: 
 - echo "Update CocoaPods"
 - gem install cocoapods
 - pod --version
script: 
 - xctool -project FSOpenInGmailSample/FSOpenInGmailSample.xcodeproj -scheme FSOpenInGmailSample -sdk iphonesimulator clean build
 - pod --version
 - pod spec lint FSOpenInGmail.podspec
